#version 140
// Generated: 2013-09-30 14:44:12 +0000
// Generator: http://io7m.com/software/parasol
// Do not edit this file! Edit the original source.
// section: types
// section: terms
// section: parameters
// section: inputs
in vec4 f_colour;
// section: outputs
out vec4 out_0;
// section: main
void
main (void)
{
  out_0 = f_colour;
}
