#version 100
// Generated: 2013-09-30 14:44:12 +0000
// Generator: http://io7m.com/software/parasol
// Do not edit this file! Edit the original source.
precision highp float;
precision highp int;
// section: types
// section: terms
// section: parameters
// section: inputs
varying vec4 f_colour;
// section: outputs
// output 0 out_0 omitted
// section: main
void
main (void)
{
  gl_FragColor = f_colour;
}
