#version 120
// Generated: 2013-09-30 14:44:33 +0000
// Generator: http://io7m.com/software/parasol
// Do not edit this file! Edit the original source.
// section: types
// section: terms
// section: parameters
// section: inputs
varying vec2 f_uv;
// section: outputs
// output 0 out_0 omitted
// section: main
void
main (void)
{
  vec4 rgba = vec4(f_uv, 0.0, 1.0);
  gl_FragColor = rgba;
}
