#version 100
// Generated: 2013-09-30 12:46:37 +0000
// Generator: http://io7m.com/software/parasol
// Do not edit this file! Edit the original source.
precision highp float;
precision highp int;
// section: types
// section: terms
// section: parameters
// section: inputs
// section: outputs
// output 0 out_0 omitted
// section: main
void
main (void)
{
  vec4 rgba = vec4(gl_FragCoord.zzz, 1.0);
  gl_FragColor = rgba;
}
