#version 110
// Generated: 2013-09-30 14:43:57 +0000
// Generator: http://io7m.com/software/parasol
// Do not edit this file! Edit the original source.
// section: types
// section: terms
// section: parameters
uniform vec4 f_ccolour;
// section: inputs
// section: outputs
// output 0 out_0 omitted
// section: main
void
main (void)
{
  gl_FragColor = f_ccolour;
}
