#version 430
// Generated: 2013-09-30 14:43:57 +0000
// Generator: http://io7m.com/software/parasol
// Do not edit this file! Edit the original source.
// section: types
// section: terms
// section: parameters
uniform vec4 f_ccolour;
// section: inputs
// section: outputs
out vec4 out_0;
// section: main
void
main (void)
{
  out_0 = f_ccolour;
}
